export const sliderData = [
  {
    lightBg: true,
    imgStart: false,
    lightTopLine: false,
    topLine: "About Our Company",
    lightText: true,
    lightTextDesc: true,
    headline: "Mobile Application",
    buttonLabel: "Get Started",
    description:
      "We help business owners increase their revenue. Our team of specialist can help you achieve your business goals.",
    start: true,
    src: "/mobile-app.jpg",
    alt: "",
  },
  {
    lightBg: true,
    imgStart: false,
    lightTopLine: false,
    topLine: "About Our Company",
    lightText: true,
    lightTextDesc: true,
    headline: "Web Development",
    buttonLabel: "Get Started",
    description:
      "We help business owners increase their revenue. Our team of specialist can help you achieve your business goals.",
    start: true,
    src: "/web-development.jpg",
    alt: "",
  },
  {
    lightBg: true,
    imgStart: false,
    lightTopLine: false,
    topLine: "About Our Company",
    lightText: true,
    lightTextDesc: true,
    headline: "Cyber Security",
    buttonLabel: "Get Started",
    description:
      "We help business owners increase their revenue. Our team of specialist can help you achieve your business goals.",
    start: true,
    src: "/cyber-security.jpg",
    alt: "",
  },
  {
    lightBg: true,
    imgStart: false,
    lightTopLine: false,
    topLine: "About Our Company",
    lightText: true,
    lightTextDesc: true,
    headline: "Database Management",
    buttonLabel: "Get Started",
    description:
      "We help business owners increase their revenue. Our team of specialist can help you achieve your business goals.",
    start: true,
    src: "/database.jpg",
    alt: "",
  },
  {
    lightBg: true,
    imgStart: false,
    lightTopLine: false,
    topLine: "About Our Company",
    lightText: true,
    lightTextDesc: true,
    headline: "Data Science",
    buttonLabel: "Get Started",
    description:
      "We help business owners increase their revenue. Our team of specialist can help you achieve your business goals.",
    start: true,
    src: "/data-science.jpg",
    alt: "",
  },
];
