export const aboutSection = {
  lightBg: true,
  imgStart: true,
  lightTopLine: false,
  topLine: "About Our Company",
  lightText: false,
  lightTextDesc: true,
  headline: "More than 5+ years we provide IT Solution",
  buttonLabel: "Get Started",
  description:
    "We help business owners increase their revenue. Our team of specialist can help you achieve your business goals.",
  start: true,
  img: "/about.jpg",
  alt: "",
};

export const sliderData = [
  {
    lightBg: true,
    imgStart: false,
    lightTopLine: false,
    topLine: "About Our Company",
    lightText: true,
    lightTextDesc: true,
    headline: "Mobile Application",
    buttonLabel: "Get Started",
    description:
      "We help business owners increase their revenue. Our team of specialist can help you achieve your business goals.",
    start: true,
    src: "/mobile-app.jpg",
    alt: "",
  },
  {
    lightBg: true,
    imgStart: false,
    lightTopLine: false,
    topLine: "About Our Company",
    lightText: true,
    lightTextDesc: true,
    headline: "Web Development",
    buttonLabel: "Get Started",
    description:
      "We help business owners increase their revenue. Our team of specialist can help you achieve your business goals.",
    start: true,
    src: "/web-development.jpg",
    alt: "",
  },
  {
    lightBg: true,
    imgStart: false,
    lightTopLine: false,
    topLine: "About Our Company",
    lightText: true,
    lightTextDesc: true,
    headline: "Cyber Security",
    buttonLabel: "Get Started",
    description:
      "We help business owners increase their revenue. Our team of specialist can help you achieve your business goals.",
    start: true,
    src: "/cyber-security.jpg",
    alt: "",
  },
  {
    lightBg: true,
    imgStart: false,
    lightTopLine: false,
    topLine: "About Our Company",
    lightText: true,
    lightTextDesc: true,
    headline: "Cyber Security",
    buttonLabel: "Get Started",
    description:
      "We help business owners increase their revenue. Our team of specialist can help you achieve your business goals.",
    start: true,
    src: "/database.jpg",
    alt: "",
  },
];
